// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAQwg_ZfHZaj2AYbHfFg5UQJOj2OdIThg',
    appId: '1:694196710386:web:b631a0ab5c7e8f1aadd96b',
    messagingSenderId: '694196710386',
    projectId: 'hungry-panda-8a399',
    authDomain: 'hungry-panda-8a399.firebaseapp.com',
    storageBucket: 'hungry-panda-8a399.firebasestorage.app',
    measurementId: 'G-434NH0TQ7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGQarJuW1xDH0zay9XipcDQb1eNNQwx0k',
    appId: '1:694196710386:android:de3aa62d161f4f72add96b',
    messagingSenderId: '694196710386',
    projectId: 'hungry-panda-8a399',
    storageBucket: 'hungry-panda-8a399.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyEPkDnU-t-zrGNS7eJAezaVmK0pNvvU8',
    appId: '1:694196710386:ios:7750a23b11ee6c24add96b',
    messagingSenderId: '694196710386',
    projectId: 'hungry-panda-8a399',
    storageBucket: 'hungry-panda-8a399.firebasestorage.app',
    iosClientId: '694196710386-u41jv312sh6bs5rqdttilmfntchgp7je.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodpractice',
  );
}
